### ISSUE TITLE
Crash when Day One entries-directory contains sub-directory

### ISSUE THREAD

**Issue by teranex** [maebert/jrnl#332]
When the 'entries'-directory in ~/Dropbox/Apps/Day One/journal.dayone contains a sub-directory `jrnl` crashes instead of ignoring the sub-directory:

```bash
$ jrnl -n1
Traceback (most recent call last):
  File "/usr/local/bin/jrnl", line 9, in <module>
    load_entry_point('jrnl==1.9.8', 'console_scripts', 'jrnl')()
  File "/usr/local/lib/python2.7/dist-packages/jrnl/cli.py", line 189, in run
    journal = DayOneJournal.DayOne(**config)
  File "/usr/local/lib/python2.7/dist-packages/jrnl/DayOneJournal.py", line 27, in __init__
    super(DayOne, self).__init__(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/jrnl/Journal.py", line 39, in __init__
    self.open()
  File "/usr/local/lib/python2.7/dist-packages/jrnl/DayOneJournal.py", line 33, in open
    with open(filename, 'rb') as plist_entry:
IOError: [Errno 21] Is a directory: u'~/Dropbox/Apps/day one/journal.dayone/entries/deleted'
```

On Android I use [Narrate App](https://play.google.com/store/apps/details?id=com.datonicgroup.narrate.app) which is compatible with the Day One format, and thus also compatible with `jrnl`. Except when you delete an entry in Narrate, it moves it to a 'deleted' sub-directory in the 'entries'-directory (I guess for syncing purposes).
Simply deleting the 'deleted' sub-directory fixes the issue, but I guess it could be solved in `jrnl` if it would ignore directories inside 'entries'

**Comment by maebert** [comment]
Should be fixed on 2.0 now :)
