### ISSUE TITLE
Tempfile problem on Windows

### ISSUE THREAD

**Issue by heitorsilva** [maebert/jrnl#390]
I'm still having the problem described on #308 and #323...

```
Traceback (most recent call last):
  File "c:\python27\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Python27\Scripts\jrnl.exe\__main__.py", line 9, in <module>
  File "c:\python27\lib\site-packages\jrnl\cli.py", line 277, in run
    edited = util.get_text_from_editor(config, journal.editable_str())
  File "c:\python27\lib\site-packages\jrnl\util.py", line 136, in get_text_from_editor
    os.remove(tmpfile)
WindowsError: [Error 32] O arquivo já está sendo usado por outro processo: 'c:\\users\\heitor\\appdata\\local\\temp\\jrnlqsnghc.txt'
```

My Jrnl version is 1.9.8, my Windows version is 10, my editor option is Sublime Text 3.

**Comment by heitorsilva** [comment]
I'll be closing this issue myself, because I've seen #361 and #327, which says there's a fix in version 2.0.
