### ISSUE TITLE
2.0 fails on upgrade checks if unicode characters are in the config file.

### ISSUE THREAD

**Issue by philipsd6** [maebert/jrnl#406]
I use some unicode characters in my `~/.jrnl_config`, but this breaks the upgrade check:
~~~zsh
$ jrnl test -1
Traceback (most recent call last):
  File "/home/philipsd6/devel/jrnl/venv/bin/jrnl", line 9, in <module>
    load_entry_point('jrnl==2.0.0rc1', 'console_scripts', 'jrnl')()
  File "/home/philipsd6/devel/jrnl/jrnl/cli.py", line 145, in run
    config = install.load_or_install_jrnl()
  File "/home/philipsd6/devel/jrnl/jrnl/install.py", line 87, in load_or_install_jrnl
    upgrade.upgrade_jrnl_if_necessary(config_path)
  File "/home/philipsd6/devel/jrnl/jrnl/upgrade.py", line 22, in upgrade_jrnl_if_necessary
    if not config_file.strip().startswith("{"):
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 170: ordinal not in range(128)
~~~
I created PR #399 to fix this issue.

**Comment by maebert** [comment]
Ouch. What a rookie mistake - thanks for catching that!
