### ISSUE TITLE
UnicodeDecodeError after OSX time machine restore

### ISSUE THREAD

**Issue by fleimgruber** [maebert/jrnl#421]
jrnl 1.9.7 via homebrew on OS X 10.10

I used jrnl with the encryption feature successfully for a few weeks. After messing up, I restored the encrypted journal.txt from OS X time machine. Now whenever I try to --edit or --decrypt the file, I get a variant of:
```
Traceback (most recent call last):
  File "/usr/local/Cellar/jrnl/1.9.7/libexec/bin/jrnl", line 9, in <module>
    load_entry_point('jrnl==1.9.7', 'console_scripts', 'jrnl')()
  File "/usr/local/Cellar/jrnl/1.9.7/libexec/lib/python2.7/site-packages/jrnl/cli.py", line 177, in run
    journal = Journal.Journal(journal_name, **config)
  File "/usr/local/Cellar/jrnl/1.9.7/libexec/lib/python2.7/site-packages/jrnl/Journal.py", line 39, in __init__
    self.open()
  File "/usr/local/Cellar/jrnl/1.9.7/libexec/lib/python2.7/site-packages/jrnl/Journal.py", line 108, in open
    journal = f.read()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/codecs.py", line 674, in read
    return self.reader.read(size)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/codecs.py", line 480, in read
    newchars, decodedbytes = self.decode(data, self.errors)
UnicodeDecodeError: 'utf8' codec can't decode byte 0x94 in position 2: invalid start byte
```
Any ideas on what might be causing this?

**Comment by maebert** [comment]
That's odd indeed. Do you enter your password or did you have the password in your keychain?

**Comment by fleimgruber** [comment]
I have it in my keychain.

**Comment by maebert** [comment]
Can you try deleting the password from your keychain and try entering it manually again?

**Comment by fleimgruber** [comment]
I tried it and after `jrnl --decrypt` the above error.

**Comment by fleimgruber** [comment]
I just found the cause for this. For whatever reason, my `.jrnl_config` read
```
{
  "default_hour": 9, 
  "linewrap": 79, 
  "encrypt": true, 
  "default_minute": 0, 
  "tagsymbols": "@", 
  "timeformat": "%Y-%m-%d %H:%M", 
  "highlight": true, 
  "journals": {
    "default": {
      "journal": "/Users/user/journal.txt", 
      "encrypt": false
    }
  }
}
```
after setting the second encrypt to true, it works.

**Comment by maebert** [comment]
Ah. This will actually give you a better warning on 2.0
