### ISSUE TITLE
2.0-rc1: _create() missing 1 required positional argument: 'password'

### ISSUE THREAD

**Issue by rnkn** [maebert/jrnl#459]
~~~
$ brew install python3
[...]
$ rm ~/.jrnl_config
$ git clone https://github.com/maebert/jrnl.git
[...]
$ cd jrnl
$ git checkout 2.0-rc1
[...]
$ pip3 install .
[...]
$ jrnl yesterday: Called in sick. Used the time to clean the house and spent 4h on writing my book.
Traceback (most recent call last):
  File "/usr/local/bin/jrnl", line 11, in <module>
    load_entry_point('jrnl==2.0.0rc1', 'console_scripts', 'jrnl')()
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 561, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2631, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2291, in load
    return self.resolve()
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2297, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.6/site-packages/jrnl/cli.py", line 15, in <module>
    from . import plugins
  File "/usr/local/lib/python3.6/site-packages/jrnl/plugins/__init__.py", line 13, in <module>
    from .template_exporter import __all__ as template_exporters
  File "/usr/local/lib/python3.6/site-packages/jrnl/plugins/template_exporter.py", line 7, in <module>
    from .template import Template
  File "/usr/local/lib/python3.6/site-packages/jrnl/plugins/template.py", line 2, in <module>
    import asteval
ModuleNotFoundError: No module named 'asteval'
$ pip3 install asteval
$ jrnl yesterday: Called in sick. Used the time to clean the house and spent 4h on writing my book.
Traceback (most recent call last):
  File "/usr/local/bin/jrnl", line 11, in <module>
    load_entry_point('jrnl==2.0.0rc1', 'console_scripts', 'jrnl')()
  File "/usr/local/lib/python3.6/site-packages/jrnl/cli.py", line 209, in run
    journal = Journal.open_journal(journal_name, config)
  File "/usr/local/lib/python3.6/site-packages/jrnl/Journal.py", line 328, in open_journal
    return EncryptedJournal.EncryptedJournal(name, **config).open()
  File "/usr/local/lib/python3.6/site-packages/jrnl/Journal.py", line 76, in open
    self._create(filename)
TypeError: _create() missing 1 required positional argument: 'password'
$
~~~

**Comment by radomirbosak** [comment]
@rnkn  I cannot reproduce this. Was the encryption on or off when you performed these steps?

Note that `jrnl` no longer uses `~/.jrnl_config` for configuration on `2.0-rc1` branch, but a YAML file `~/.config/jrnl/jrnl.yaml` instead.

Can you please delete both files, reinstall jrnl and rerun the reproducing steps?

The reason I ask about the encryption is that the offending line
```python
EncryptedJournal.EncryptedJournal(name, **config).open()
```
located in this code block
```python
...
if not config['encrypt']:
    if legacy:
        return LegacyJournal(name, **config).open()
    return PlainJournal(name, **config).open()
else:
    from . import EncryptedJournal
    if legacy:
        return EncryptedJournal.LegacyEncryptedJournal(name, **config).open()
    return EncryptedJournal.EncryptedJournal(name, **config).open()
```
requires that there's `encrypt: true` in the config file.

**Comment by rnkn** [comment]
Ah I'm not using jrnl anymore. Thanks though.

**Comment by gregorybodnar** [comment]
I just ran into this issue while testing 2.0-rc2. I had a yaml configuration file that pointed to a non-existent file and specified encryption, leading to the exact error shown above.

If the configuration file didn't indicate encryption, there is no problem with removing a journal file and replacing it. Once this journal file is created, it can be encrypted with `jrnl --encrypt` and be used without issue.

.config/jrnl/jrnl.yaml:
```
default_hour: 9
default_minute: 0
editor: vim
encrypt: false
highlight: true
indent_character: '|'
journals:
  default:
    encrypt: true
    journal: /home/greg/Sync/j2/journal.txt
  test:
    encrypt: false
    journal: /home/greg/testjournal.txt
linewrap: 99
tagsymbols: '@'
template: false
timeformat: '%Y-%m-%d %H:%M'
version: 2.0.0-rc1
```

Remove the journal file to set up the failure.
`rm /home/greg/Sync/j2/journal.txt`

```
jrnl Add an entry from rc2 to an encrypted jrnl.
[Journal 'default' created at /home/greg/Sync/j2/journal.txt]
Traceback (most recent call last):
  File "/home/greg/venvs/jrnl-2.0/bin/jrnl", line 11, in <module>
    load_entry_point('jrnl', 'console_scripts', 'jrnl')()
  File "/home/greg/git/jrnl/jrnl/cli.py", line 210, in run
    journal = Journal.open_journal(journal_name, config)
  File "/home/greg/git/jrnl/jrnl/Journal.py", line 328, in open_journal
    return EncryptedJournal.EncryptedJournal(name, **config).open()
  File "/home/greg/git/jrnl/jrnl/Journal.py", line 76, in open
    self._create(filename)
TypeError: _create() missing 1 required positional argument: 'password'
```
