### ISSUE TITLE
[Bug] FileNotFoundError: [Errno 2] No such file or directory:

### ISSUE THREAD

**Issue by Kristinita** [maebert/jrnl#466]
### 1. Summary

I want to create my `journal.txt` file in `D:\Киролайна\jrnl` path. But I get stack trace.

### 2. Expected behavior

Like path name contains only Latin letters.

    [Journal created at D:\Киролайна\jrnl/journal.txt]
    [Entry added to default journal]

### 3. Actual behavior

```python
D:\sublime-jrnl>jrnl yesterday: Kristina unthinkable!
[Journal created at D:\РљРёСЂРѕР»Р°Р№РЅР°\jrnl/journal.txt]
Traceback (most recent call last):
  File "c:\python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python36\Scripts\jrnl.EXE\__main__.py", line 9, in <module>
  File "c:\python36\lib\site-packages\jrnl\cli.py", line 181, in run
    touch_journal(config['journal'])
  File "c:\python36\lib\site-packages\jrnl\cli.py", line 98, in touch_journal
    open(filename, 'a').close()
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\РљРёСЂРѕР»Р°Р№РЅР°\\jrnl/journal.txt'
```

### 4. Settings

Part of my `.jrnl_config` file:

```json
"journals": {
  "default": "D:\\Киролайна\\jrnl/journal.txt"
},
```

### 5. Steps to reproduce

I install jrnl → I set `.jrnl_config` file → if my path contain Cyrillic symbols, I get stack trace.

I try run command [**`chcp 1251`**](http://jrnl.sh/advanced.html?highlight=unicode#known-issues) in console → I get same behavior.

### 6. Environment

**Operating system and version:**
Windows 10 Enterprise LTSB 64-bit EN
**Python:**
3.6.0
**jrnl:**
version 1.9.8

Thanks.

**Comment by MinchinWeb** [comment]
I can duplicate the problem, but I'm not sure how to solve it

**Comment by radomirbosak** [comment]
@Kristinita  that last forward slash in `D:\Киролайна\jrnl/journal.txt` is suspicious. Wouldn't replacing it with a backslash help? I'm not a Windows user, so I cannot reproduce the issue, but I doubt Windows likes mixing slashes.

**Comment by Kristinita** [comment]
@radomirbosak , if I try `"default": "D:\\Киролайна\\jrnl\\journal.txt"`, I get same behavior.

Thanks.

**Comment by Kristinita** [comment]
The problem not solved.

Thanks.

**Comment by wren** [comment]
@Kristinita Can you try this on v2.0? I don't see the error running the v2.0, but I'm not sure if it's a Windows-specific problem.

**Comment by micahellison** [comment]
This appears fixed, but it would be good to have a test for it after we've set up a proper Windows testing pipeline.

**Comment by wren** [comment]
We recently brought the Windows pipeline into full parity with the other pipelines, so it would be good time to add this test.
