### ISSUE TITLE
1.9.8 not working on OS X

### ISSUE THREAD

**Issue by fladd** [maebert/jrnl#482]
After updating to the newest version via brew:

```
Traceback (most recent call last):
  File "/usr/local/bin/jrnl", line 11, in <module>
    load_entry_point('jrnl==1.9.8', 'console_scripts', 'jrnl')()
  File "/usr/local/Cellar/jrnl/1.9.8/libexec/lib/python2.7/site-packages/jrnl/cli.py", line 194, in run
    journal = Journal.Journal(journal_name, **config)
  File "/usr/local/Cellar/jrnl/1.9.8/libexec/lib/python2.7/site-packages/jrnl/Journal.py", line 39, in __init__
    self.open()
  File "/usr/local/Cellar/jrnl/1.9.8/libexec/lib/python2.7/site-packages/jrnl/Journal.py", line 105, in open
    journal = util.get_password(keychain=self.name, validator=validate_password)
  File "/usr/local/Cellar/jrnl/1.9.8/libexec/lib/python2.7/site-packages/jrnl/util.py", line 37, in get_password
    pwd_from_keychain = keychain and get_keychain(keychain)
  File "/usr/local/Cellar/jrnl/1.9.8/libexec/lib/python2.7/site-packages/jrnl/util.py", line 56, in get_keychain
    return keyring.get_password('jrnl', journal_name)
  File "/usr/local/Cellar/jrnl/1.9.8/libexec/lib/python2.7/site-packages/keyring/core.py", line 42, in get_password
    return _keyring_backend.get_password(service_name, username)
  File "/usr/local/Cellar/jrnl/1.9.8/libexec/lib/python2.7/site-packages/keyring/backends/OS_X.py", line 44, in get_password
    return api.find_generic_password(self.keychain, service, username)
  File "/usr/local/Cellar/jrnl/1.9.8/libexec/lib/python2.7/site-packages/keyring/backends/_OS_X_API.py", line 95, in find_generic_password
    NotFound.raise_for_status(status, msg)
  File "/usr/local/Cellar/jrnl/1.9.8/libexec/lib/python2.7/site-packages/keyring/backends/_OS_X_API.py", line 46, in raise_for_status
    Error.raise_for_status(status, msg)
  File "/usr/local/Cellar/jrnl/1.9.8/libexec/lib/python2.7/site-packages/keyring/backends/_OS_X_API.py", line 38, in raise_for_status
    raise cls(status, msg)
keyring.backends._OS_X_API.Error: (-25293, "Can't fetch password from system")
```

**Comment by maebert** [comment]
What happens when you do `pip install -U keychain`?

**Comment by fladd** [comment]
```
fladd:~$ pip install -U keychain
Collecting keychain
  Downloading keychain-0.1.4.1.tar.gz
Collecting bitmerchant>=0.1.8 (from keychain)
  Downloading bitmerchant-0.1.8-py2.py3-none-any.whl
Collecting bitcoin>=1.1.42 (from keychain)
  Downloading bitcoin-1.1.42.tar.gz
Collecting base58>=0.2.1 (from bitmerchant>=0.1.8->keychain)
  Downloading base58-0.2.5-py2-none-any.whl
Requirement already up-to-date: six>=1.5.2 in /usr/local/lib/python2.7/site-packages (from bitmerchant>=0.1.8->keychain)
Collecting cachetools>=1.1.1 (from bitmerchant>=0.1.8->keychain)
  Downloading cachetools-2.0.0-py2.py3-none-any.whl
Collecting ecdsa>=0.10 (from bitmerchant>=0.1.8->keychain)
  Downloading ecdsa-0.13-py2.py3-none-any.whl (86kB)
    100% |████████████████████████████████| 92kB 3.4MB/s 
Building wheels for collected packages: keychain, bitcoin
  Running setup.py bdist_wheel for keychain ... done
  Stored in directory: /Users/floriankrause/Library/Caches/pip/wheels/61/92/44/f1c0eb2fa771f826565d6b128bb551a97fa5c4d9d8ac59f6af
  Running setup.py bdist_wheel for bitcoin ... done
  Stored in directory: /Users/floriankrause/Library/Caches/pip/wheels/15/d9/46/0029939110ce681cbcb1b94b8952f475eb3562e65cd99d311f
Successfully built keychain bitcoin
Installing collected packages: base58, cachetools, ecdsa, bitmerchant, bitcoin, keychain
Successfully installed base58-0.2.5 bitcoin-1.1.42 bitmerchant-0.1.8 cachetools-2.0.0 ecdsa-0.13 keychain-0.1.4.1
fladd:~$ jrnl --edit
Traceback (most recent call last):
  File "/usr/local/bin/jrnl", line 11, in <module>
    load_entry_point('jrnl==1.9.8', 'console_scripts', 'jrnl')()
  File "/usr/local/Cellar/jrnl/1.9.8/libexec/lib/python2.7/site-packages/jrnl/cli.py", line 194, in run
    journal = Journal.Journal(journal_name, **config)
  File "/usr/local/Cellar/jrnl/1.9.8/libexec/lib/python2.7/site-packages/jrnl/Journal.py", line 39, in __init__
    self.open()
  File "/usr/local/Cellar/jrnl/1.9.8/libexec/lib/python2.7/site-packages/jrnl/Journal.py", line 105, in open
    journal = util.get_password(keychain=self.name, validator=validate_password)
  File "/usr/local/Cellar/jrnl/1.9.8/libexec/lib/python2.7/site-packages/jrnl/util.py", line 37, in get_password
    pwd_from_keychain = keychain and get_keychain(keychain)
  File "/usr/local/Cellar/jrnl/1.9.8/libexec/lib/python2.7/site-packages/jrnl/util.py", line 56, in get_keychain
    return keyring.get_password('jrnl', journal_name)
  File "/usr/local/Cellar/jrnl/1.9.8/libexec/lib/python2.7/site-packages/keyring/core.py", line 42, in get_password
    return _keyring_backend.get_password(service_name, username)
  File "/usr/local/Cellar/jrnl/1.9.8/libexec/lib/python2.7/site-packages/keyring/backends/OS_X.py", line 44, in get_password
    return api.find_generic_password(self.keychain, service, username)
  File "/usr/local/Cellar/jrnl/1.9.8/libexec/lib/python2.7/site-packages/keyring/backends/_OS_X_API.py", line 95, in find_generic_password
    NotFound.raise_for_status(status, msg)
  File "/usr/local/Cellar/jrnl/1.9.8/libexec/lib/python2.7/site-packages/keyring/backends/_OS_X_API.py", line 46, in raise_for_status
    Error.raise_for_status(status, msg)
  File "/usr/local/Cellar/jrnl/1.9.8/libexec/lib/python2.7/site-packages/keyring/backends/_OS_X_API.py", line 38, in raise_for_status
    raise cls(status, msg)
keyring.backends._OS_X_API.Error: (-25293, "Can't fetch password from system")
```

**Comment by maebert** [comment]
Ah, super sorry, I meant `keyring`, not `keychain`. My brain wasn't quite working yet.

So, try

```bash
pip uninstall keychain
pip install -U keyring
```

**Comment by fladd** [comment]
That leads to the same error when running `jrnl` installed with brew.

When installing `jrnl` with pip, it works, but for every single jrnl command prints these lines to the terminal:
```
Dynamic session lookup supported but failed: launchd did not provide a socket path, verify that org.freedesktop.dbus-session.plist is loaded!
Dynamic session lookup supported but failed: launchd did not provide a socket path, verify that org.freedesktop.dbus-session.plist is loaded!
```

**Comment by fladd** [comment]
I solved it. The correct installation instructions for homebrew are:

1. `brew install jrnl`
2. `brew install dbus`
3. `brew services start dbus`

I suggest to add this to the jrnl website.

**Comment by maebert** [comment]
Oh, that's an interesting find. I remember having issues with d-bus before, but I'll add that. Thanks!
