### ISSUE TITLE
Dayone Error

### ISSUE THREAD

**Issue by shenshifo** [maebert/jrnl#484]
jrnl does not work recently. I am using Mac OS Sierra. I tried to install it use both pip3 and brew. Got the same error related to groupdict() as follows:

```
Traceback (most recent call last):
  File "/usr/local/bin/jrnl", line 11, in <module>
    load_entry_point('jrnl==1.9.8', 'console_scripts', 'jrnl')()
  File "/usr/local/Cellar/jrnl/1.9.8/libexec/lib/python2.7/site-packages/jrnl/cli.py", line 189, in run
    journal = DayOneJournal.DayOne(**config)
  File "/usr/local/Cellar/jrnl/1.9.8/libexec/lib/python2.7/site-packages/jrnl/DayOneJournal.py", line 27, in __init__
    super(DayOne, self).__init__(**kwargs)
  File "/usr/local/Cellar/jrnl/1.9.8/libexec/lib/python2.7/site-packages/jrnl/Journal.py", line 39, in __init__
    self.open()
  File "/usr/local/Cellar/jrnl/1.9.8/libexec/lib/python2.7/site-packages/jrnl/DayOneJournal.py", line 37, in open
    dict_entry = plistlib.readPlist(plist_entry)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plistlib.py", line 78, in readPlist
    rootObject = p.parse(pathOrFile)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plistlib.py", line 406, in parse
    parser.ParseFile(fileobj)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plistlib.py", line 418, in handleEndElement
    handler()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plistlib.py", line 474, in end_date
    self.addObject(_dateFromString(self.getData()))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plistlib.py", line 191, in _dateFromString
    gd = _dateParser.match(s).groupdict()
AttributeError: 'NoneType' object has no attribute 'groupdict'
```

**Comment by maebert** [comment]
Hi,

This is an error with parsing dates in DayOne files that I haven't seen before. Which version of DayOne Are you using?

To resolve this, I'll need the DayOne file that causes this error. In your DayOne folder, temporarily remove everything but one file and see if the error persists; if so please send me this file (you can edit it first to remove the body of your entry of course, just leave the other fields intact). If jrnl works with only this one file there, you might have to try around a bit until you find the offender.

Thanks!

**Comment by shenshifo** [comment]
I am using DayOne classic. Here is an example, which is created by jrnl. Thanks!

**Comment by maebert** [comment]
I think you may have sent the example as an attachement - your mail went to [Github issues](https://github.com/maebert/jrnl/issues/484#issuecomment-301523986). You can send the attachment to me directly at `manuel@1450.me` or add it to the issue.

**Comment by maebert** [comment]
I can get the entry to load without peoblems. If you remove all but the file you sent me from your DayOne folder, does it still not work?

**Comment by shenshifo** [comment]
Yes. It works. I think it should be caused by other files and not a bug in jrnl. Thanks.

**Comment by maebert** [comment]
That's what I suspected. Closing this now, but if you find the offending file let me know and I can make sure that jrnl ignores such files in the future.
