### ISSUE TITLE
Errors with keychain over ssh

### ISSUE THREAD

**Issue by insanerwayner** [maebert/jrnl#496]
When I try to use over **ssh** I get thrown a lot of errors about the **keychain**. I'd like to be able to use this remotely on the go.

On **Ubuntu 16.04 LTS** btw

Here are the errors:

```
wayne@waynebuntu:~$ jrnl
Traceback (most recent call last):
  File "/usr/local/bin/jrnl", line 11, in <module>
    sys.exit(run())
  File "/usr/local/lib/python2.7/dist-packages/jrnl/cli.py", line 194, in run
    journal = Journal.Journal(journal_name, **config)
  File "/usr/local/lib/python2.7/dist-packages/jrnl/Journal.py", line 39, in __i                                                                                                                                                             nit__
    self.open()
  File "/usr/local/lib/python2.7/dist-packages/jrnl/Journal.py", line 105, in op                                                                                                                                                             en
    journal = util.get_password(keychain=self.name, validator=validate_password)
  File "/usr/local/lib/python2.7/dist-packages/jrnl/util.py", line 37, in get_pa                                                                                                                                                             ssword
    pwd_from_keychain = keychain and get_keychain(keychain)
  File "/usr/local/lib/python2.7/dist-packages/jrnl/util.py", line 56, in get_ke                                                                                                                                                             ychain
    return keyring.get_password('jrnl', journal_name)
  File "/usr/local/lib/python2.7/dist-packages/keyring/core.py", line 41, in get                                                                                                                                                             _password
    return _keyring_backend.get_password(service_name, username)
  File "/usr/local/lib/python2.7/dist-packages/keyring/backends/fail.py", line 2                                                                                                                                                             3, in get_password
    raise RuntimeError(msg)
RuntimeError: No recommended backend was available. Install the keyrings.alt pac                                                                                                                                                             kage if you want to use the non-recommended backends. See README.rst for details                                                                                                                                                             .
```

**Comment by insanerwayner** [comment]
Answered my own question. Installed **keyrings.alt** with **pip** and it started working.
