### ISSUE TITLE
Errors on Arch linux relating to keyring 

### ISSUE THREAD

**Issue by electric-ladyland** [maebert/jrnl#562]
Running `jrnl` for encrypted journals gives:

```
Traceback (most recent call last):
  File "/home/chris/.local/bin/jrnl", line 10, in <module>
    sys.exit(run())
  File "/home/chris/.local/lib/python3.7/site-packages/jrnl/cli.py", line 194, in run
    journal = Journal.Journal(journal_name, **config)
  File "/home/chris/.local/lib/python3.7/site-packages/jrnl/Journal.py", line 39, in __init__
    self.open()
  File "/home/chris/.local/lib/python3.7/site-packages/jrnl/Journal.py", line 105, in open
    journal = util.get_password(keychain=self.name, validator=validate_password)
  File "/home/chris/.local/lib/python3.7/site-packages/jrnl/util.py", line 37, in get_password
    pwd_from_keychain = keychain and get_keychain(keychain)
  File "/home/chris/.local/lib/python3.7/site-packages/jrnl/util.py", line 56, in get_keychain
    return keyring.get_password('jrnl', journal_name)
  File "/home/chris/.local/lib/python3.7/site-packages/keyring/core.py", line 58, in get_password
    return _keyring_backend.get_password(service_name, username)
  File "/home/chris/.local/lib/python3.7/site-packages/keyring/backends/fail.py", line 23, in get_password
    raise RuntimeError(msg)
RuntimeError: No recommended backend was available. Install the keyrings.alt package if you want to use the non-recommended backends. See README.rst for details.
```
Tried installing keyrings.alt through pip, both with --user and sudo.
Tried installing latest Arch packages python-keyring and python-keyrings-alt (versions 16.0.0-1 and 3.1-3 respectively).
Nothing has any effect.

I see #407 is marked as closed...

**Comment by rvashurin** [comment]
As stated in error message you need an actual keyring to use this. Try installing gnome-keyring or some similar package.

**Comment by UnicodeAlt255** [comment]
It would be nice to not be hard dependent on a keyring, not everyone is using gnome/plasma/whatever.

**Comment by electric-ladyland** [comment]
Or at least say that a keyring package needs to be installed (if possible). "No recommended backend was available." is what caused me to report the issue, as it's a bit vague, considering I was unfamiliar with keyrings never having needed one on Arch before.
