### ISSUE TITLE
Not able to open my jrnl

### ISSUE THREAD

**Issue by insanerwayner** [maebert/jrnl#569]
on Pop!_OS 18.10 and my journal will not open. I have tried completed removing jrnl, also tried resetting the config file and reconfiguring to point to file and it keeps giving this error:

```
Traceback (most recent call last):
  File "/usr/local/bin/jrnl", line 11, in <module>
    sys.exit(run())
  File "/usr/local/lib/python2.7/dist-packages/jrnl/cli.py", line 138, in run
    config = install.install_jrnl(CONFIG_PATH)
  File "/usr/local/lib/python2.7/dist-packages/jrnl/install.py", line 76, in install_jrnl
    util.set_keychain("default", password)
  File "/usr/local/lib/python2.7/dist-packages/jrnl/util.py", line 65, in set_keychain
    keyring.set_password('jrnl', journal_name, password)
  File "/usr/local/lib/python2.7/dist-packages/keyring/core.py", line 44, in set_password
    _keyring_backend.set_password(service_name, username, password)
  File "/usr/local/lib/python2.7/dist-packages/keyring/backends/SecretService.py", line 62, in set_password
    collection = self.get_default_collection()
  File "/usr/local/lib/python2.7/dist-packages/keyring/backends/SecretService.py", line 47, in get_default_collection
    raise InitError("Failed to unlock the collection!")
keyring.errors.InitError: Failed to unlock the collection!
```

**Comment by insanerwayner** [comment]
This was over SSH. I found that I had to unlock the keyring locally on the machine.
