### ISSUE TITLE
ImportError: libreadline.so.6: cannot open shared object file

### ISSUE THREAD

**Issue by dhruvkar** [maebert/jrnl#570]
**Ubuntu 18.04 | Python 3.5.2**

After `pip install jrnl[encrypted]` in a virtual environment. This is what happens when I run `jrnl` for the first time. Wasn't able to find this issue anywhere and not sure if I'm missing a dependency? 

Great project, was running on my macbook perfectly.

```Traceback (most recent call last):
  File "/home/dhruv/.virtualenvs/journal/bin/jrnl", line 9, in <module>
    load_entry_point('jrnl==1.9.8', 'console_scripts', 'jrnl')()
  File "/home/dhruv/.virtualenvs/journal/lib/python3.5/site-packages/pkg_resources/__init__.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/dhruv/.virtualenvs/journal/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2569, in load_entry_point
    return ep.load()
  File "/home/dhruv/.virtualenvs/journal/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2229, in load
    return self.resolve()
  File "/home/dhruv/.virtualenvs/journal/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2235, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/dhruv/.virtualenvs/journal/lib/python3.5/site-packages/jrnl/__init__.py", line 17, in <module>
    from . import cli
  File "/home/dhruv/.virtualenvs/journal/lib/python3.5/site-packages/jrnl/cli.py", line 15, in <module>
    from . import install
  File "/home/dhruv/.virtualenvs/journal/lib/python3.5/site-packages/jrnl/install.py", line 5, in <module>
    import readline
ImportError: libreadline.so.6: cannot open shared object file: No such file or directory
```

**Comment by dhruvkar** [comment]
So this is a known issue for 18.04 [**0**]. I was able to fix it by install the libreadline6 deb binary manually from the 16.04 package [**1**]. Closing issue.

0: https://utcc.utoronto.ca/~cks/space/blog/linux/Ubuntu1804ReadlineMess
1: https://packages.ubuntu.com/xenial/libreadline6
